version: "2"
services:
  gokita:
    build:
      context: .
      dockerfile: build/Dockerfile
    restart: always
    volumes:
    - .:/go/src/github.com/SeamPay/gokita
    container_name: gokita
    environment:
      - ENVIRONMENT=development
      - DEBUG_ADDR=:8080
      - GRPC_ADDR=:8082
      - HTTP_ADDR=:8081
    ports:
    - 8800:8082
